const QUERY_CREATE_CITY = `
INSERT INTO cities (name, rating, country_id)
VALUES (?, ?, ?)
RETURNING *;
`

const QUERY_GET_COUNTRIES = `
SELECT * FROM countries;
`

const QUERY_GET_CITIES = `
SELECT cities.city_id, cities.name AS city, country.name AS country, cities.rating AS rating 
FROM cities
JOIN countries AS country
ON cities.country_id = country.country_id
ORDER BY rating DESC;
`
const QUERY_DELETE_CITY = `
DELETE FROM cities
WHERE city_id = ?;
`

const QUERY_SEED = `
drop table if exists cities;
drop table if exists countries;

create table countries (
    country_id serial primary key, 
    name varchar
    );
    
    CREATE TABLE cities (
        city_id SERIAL PRIMARY KEY,
        name VARCHAR,
        rating INT,
        country_id INT REFERENCES countries(country_id)
        
        );
        INSERT INTO cities (name, rating, country_id)
        VALUES ('Ascuncion', 5, 137),
                ('LaPaz', 3, 21),
                ('Caracas', 4, 191),
                ('Bogota', 5, 38),
                ('Quito', 4, 51),
                ('Lima', 2, 138),
                ('Santiago', 1, 36),
                ('Buenos Aires', 2, 7),
                ('Montevideo', 5, 188),
                ('Brazilia', 3, 24);

        
        insert into countries (name)
        values ('Afghanistan'),
        ('Albania'),
        ('Algeria'),
        ('Andorra'),
        ('Angola'),
        ('Antigua and Barbuda'),
        ('Argentina'),
        ('Armenia'),
        ('Australia'),
        ('Austria'),
        ('Azerbaijan'),
        ('Bahamas'),
        ('Bahrain'),
        ('Bangladesh'),
        ('Barbados'),
        ('Belarus'),
        ('Belgium'),
        ('Belize'),
        ('Benin'),
        ('Bhutan'),
        ('Bolivia'),
        ('Bosnia and Herzegovina'),
        ('Botswana'),
        ('Brazil'),
        ('Brunei'),
        ('Bulgaria'),
        ('Burkina Faso'),
        ('Burundi'),
        ('Côte d''Ivoire'),
        ('Cabo Verde'),
        ('Cambodia'),
        ('Cameroon'),
        ('Canada'),
        ('Central African Republic'),
        ('Chad'),
        ('Chile'),
        ('China'),
        ('Colombia'),
        ('Comoros'),
        ('Congo'),
        ('Costa Rica'),
        ('Croatia'),
        ('Cuba'),
        ('Cyprus'),
        ('Czech Republic'),
        ('Democratic Republic of the Congo'),
        ('Denmark'),
        ('Djibouti'),
        ('Dominica'),
        ('Dominican Republic'),
        ('Ecuador'),
        ('Egypt'),
        ('El Salvador'),
        ('Equatorial Guinea'),
        ('Eritrea'),
        ('Estonia'),
        ('Eswatini'),
        ('Ethiopia'),
        ('Fiji'),
        ('Finland'),
        ('France'),
        ('Gabon'),
        ('Gambia'),
        ('Georgia'),
        ('Germany'),
        ('Ghana'),
        ('Greece'),
        ('Grenada'),
        ('Guatemala'),
        ('Guinea'),
        ('Guinea-Bissau'),
        ('Guyana'),
        ('Haiti'),
        ('Holy See'),
        ('Honduras'),
        ('Hungary'),
        ('Iceland'),
        ('India'),
        ('Indonesia'),
        ('Iran'),
        ('Iraq'),
        ('Ireland'),
        ('Israel'),
        ('Italy'),
        ('Jamaica'),
        ('Japan'),
        ('Jordan'),
        ('Kazakhstan'),
        ('Kenya'),
        ('Kiribati'),
        ('Kuwait'),
        ('Kyrgyzstan'),
        ('Laos'),
        ('Latvia'),
        ('Lebanon'),
        ('Lesotho'),
        ('Liberia'),
        ('Libya'),
        ('Liechtenstein'),
        ('Lithuania'),
        ('Luxembourg'),
        ('Madagascar'),
        ('Malawi'),
        ('Malaysia'),
        ('Maldives'),
        ('Mali'),
        ('Malta'),
        ('Marshall Islands'),
        ('Mauritania'),
        ('Mauritius'),
        ('Mexico'),
        ('Micronesia'),
        ('Moldova'),
        ('Monaco'),
        ('Mongolia'),
        ('Montenegro'),
        ('Morocco'),
        ('Mozambique'),
        ('Myanmar'),
        ('Namibia'),
        ('Nauru'),
        ('Nepal'),
        ('Netherlands'),
        ('New Zealand'),
        ('Nicaragua'),
        ('Niger'),
        ('Nigeria'),
        ('North Korea'),
        ('North Macedonia'),
        ('Norway'),
        ('Oman'),
        ('Pakistan'),
        ('Palau'),
        ('Palestine State'),
        ('Panama'),
        ('Papua New Guinea'),
        ('Paraguay'),
        ('Peru'),
        ('Philippines'),
        ('Poland'),
        ('Portugal'),
        ('Qatar'),
        ('Romania'),
        ('Russia'),
        ('Rwanda'),
        ('Saint Kitts and Nevis'),
        ('Saint Lucia'),
        ('Saint Vincent and the Grenadines'),
        ('Samoa'),
        ('San Marino'),
        ('Sao Tome and Principe'),
        ('Saudi Arabia'),
        ('Senegal'),
        ('Serbia'),
        ('Seychelles'),
        ('Sierra Leone'),
        ('Singapore'),
        ('Slovakia'),
        ('Slovenia'),
        ('Solomon Islands'),
        ('Somalia'),
        ('South Africa'),
        ('South Korea'),
        ('South Sudan'),
        ('Spain'),
        ('Sri Lanka'),
        ('Sudan'),
        ('Suriname'),
        ('Sweden'),
        ('Switzerland'),
        ('Syria'),
        ('Tajikistan'),
        ('Tanzania'),
        ('Thailand'),
        ('Timor-Leste'),
        ('Togo'),
        ('Tonga'),
        ('Trinidad and Tobago'),
        ('Tunisia'),
        ('Turkey'),
        ('Turkmenistan'),
        ('Tuvalu'),
        ('Uganda'),
        ('Ukraine'),
        ('United Arab Emirates'),
        ('United Kingdom'),
        ('United States of America'),
        ('Uruguay'),
        ('Uzbekistan'),
        ('Vanuatu'),
        ('Venezuela'),
        ('Vietnam'),
        ('Yemen'),
        ('Zambia'),
        ('Zimbabwe');
        
        `

module.exports = {
  QUERY_SEED,
  QUERY_GET_COUNTRIES,
  QUERY_CREATE_CITY,
  QUERY_GET_CITIES,
  QUERY_DELETE_CITY
}
